# Generated by Django 4.2.5 on 2024-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.collection'),
        ),
    ]
