# Generated by Django 4.2.5 on 2024-03-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
