# Generated by Django 4.2.5 on 2024-03-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('attributes', models.ManyToManyField(blank=True, related_name='product_templates', to='products.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='product_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.producttemplate'),
        ),
    ]
