# Generated by Django 4.2.5 on 2024-03-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producttemplate_variation_product_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.producttemplate'),
        ),
    ]
