# Generated by Django 4.2.5 on 2024-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_variation_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
