# Generated by Django 4.2.5 on 2024-03-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variation_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(blank=True, default='SKU1', max_length=50),
            preserve_default=False,
        ),
    ]
