# Generated by Django 4.2.5 on 2024-03-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.option'),
        ),
    ]
