# Generated by Django 4.2.5 on 2024-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_variation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='options',
        ),
        migrations.AddField(
            model_name='variation',
            name='options',
            field=models.ManyToManyField(related_name='variations', to='products.option'),
        ),
    ]
