# Generated by Django 4.2.5 on 2024-03-22 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/logos/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('shop_members', models.ManyToManyField(blank=True, null=True, related_name='shop_members', to=settings.AUTH_USER_MODEL)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_shop', 'Can manage the shop'), ('edit_shop', 'Can edit the shop')],
            },
        ),
    ]
