# Generated by Django 4.2.5 on 2024-03-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_shop_shop_members_alter_shop_shop_owner_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
    ]
