# Generated by Django 4.2.5 on 2024-03-22 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_store_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreConfiguration',
        ),
    ]
