# Generated by Django 4.2.5 on 2024-03-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_store_storeconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='store_admin',
        ),
    ]
