# Generated by Django 4.2.5 on 2024-03-22 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_remove_storeconfiguration_store_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
