# Generated by Django 4.2.5 on 2024-03-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_shop_shop_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeconfiguration',
            options={'verbose_name': 'Store Configuration', 'verbose_name_plural': 'Store Configuration'},
        ),
    ]
